server:
  port: 8181
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags:
          - urlprefix-/ui opts strip=/ui
          - traefik.frontend.rule=PathPrefixStrip:${server.contextPath:}/ui
          - statusPageUrlPath=${server.contextPath:}/info
          - healthCheckUrlPath=${server.contextPath:}/health
        healthCheckPath: ${management.contextPath:}/health
        host-info: ${management.contextPath:}/info
        hostname: ${HOSTNAME:ui}
        ip-address: ${HOSTNAME:10.200.10.1}
        prefer-ip-address: true
      ## Disabled by default
      enabled: false

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    status-page-url-path: ${management.contextPath:}/info
    health-check-url-path: ${management.contextPath:}/health
  client:
    serviceUrl:
      defaultZone: http://${reportportal.eureka.hostname:localhost}:8761/eureka/
    register-with-eureka: true
    enabled: true

## Eureka as service registry
---
spring:
  profiles: eureka
  cloud:
    consul:
      enabled: false
      discovery:
        register: false
eureka:
  client:
    enabled: true
    register-with-eureka: true
## Consul as service registry
---
spring:
  profiles: consul
  cloud:
    consul:
      enabled: true
      discovery:
        register: true
eureka:
  client:
    register-with-eureka: false
    enabled: false
---
